import os
from qutebrowser.config.configfiles import ConfigAPI  # noqa: F401,E501 pylint: disable=unused-import
from qutebrowser.config.config import ConfigContainer  # noqa: F401,E501 pylint: disable=unused-import
config = config
c = c

# Helper function
def nmap(key,command):
		bind(key, command, 'normal')

def bind(key, command, mode):
		config.bind(key, command, mode=mode)


# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Bindings for normal mode
config.bind('J', 'tab-prev')
config.bind('K', 'tab-next')

# ** Search Keywords
c.url.searchengines = \
    {'DEFAULT': 'https://www.startpage.com/do/search?query={}&?prf=7de10a290cc3cee4fa552d4b43dc3f48',
	'aw': 'http://wiki.archlinux.org/index.php?search={}',
	'gh': 'http://github.com/search?q={}', 
	'r': 'http://www.reddit.com/r/{}/'}


# Open new private window
nmap ('tp','open -p')

# ** Yanking and Pasting
# don't need primary or extra yanks
nmap('p', 'open --tab -- {clipboard}')
nmap('P', 'open -- {clipboard}')
nmap('y', 'yank')
nmap('Y', 'yank selection')


# Pywal
config.source('qutewal.py')
